### PR TITLE
Fix: issue #70

### PR DESCRIPTION
**Pull request by clthck**
Reference #70

### CODE REVIEW

**Comment by tshedor** [comment]
Can confirm this works. It also resolves #74

**Comment by tshedor** [comment]
This removes highlighting for the next line. For example,

```slim
/ This comment will designate "tag" on the next line as a comment
tag
```

**Comment by clthck** [comment]
@tshedor What do you mean?

**Comment by tshedor** [comment]
@clthck Your proposed change affects text at the same indentation level:
image

Versus how it should be highlighted according to the Slim spec (using the definitions from the package in its current release):
image

ST3 added/revised syntax highlighting features, and that's affected this package. However, the latest release (3143) seems to resolve some highlighting issues that appeared in beta releases (like this one and the block comments on #74) while some are still broken (#72 via #53).

**Comment by clthck** [comment]
Seen from the screenshot, isn't it because of being wrapped in IE comment section?

**Comment by tshedor** [comment]
@clthck Oh, that's a great point. You're right. Sorry about that.

Last thing, I swear: would you please apply the same change to the [YAML file](https://github.com/slim-template/ruby-slim.tmbundle/blob/master/Syntaxes/Ruby%20Slim.YAML-tmLanguage)? It helps maintenance and legibility/seems [Sublime's preference](http://www.sublimetext.com/docs/3/syntax.html).

**Comment by clthck** [comment]
@tshedor YAML file updated.

**Comment by tshedor** [comment]
Thanks @clthck

**Comment by skunkworker** [comment]
Thanks. This fixed it for me.

**Pull request merged**
